package com.example.administrator.mofang.time.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.administrator.mofang.time.greendao.Score;
import com.example.administrator.mofang.time.greendao.Group;

import com.example.administrator.mofang.time.greendao.ScoreDao;
import com.example.administrator.mofang.time.greendao.GroupDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig scoreDaoConfig;
    private final DaoConfig groupDaoConfig;

    private final ScoreDao scoreDao;
    private final GroupDao groupDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        scoreDaoConfig = daoConfigMap.get(ScoreDao.class).clone();
        scoreDaoConfig.initIdentityScope(type);

        groupDaoConfig = daoConfigMap.get(GroupDao.class).clone();
        groupDaoConfig.initIdentityScope(type);

        scoreDao = new ScoreDao(scoreDaoConfig, this);
        groupDao = new GroupDao(groupDaoConfig, this);

        registerDao(Score.class, scoreDao);
        registerDao(Group.class, groupDao);
    }
    
    public void clear() {
        scoreDaoConfig.getIdentityScope().clear();
        groupDaoConfig.getIdentityScope().clear();
    }

    public ScoreDao getScoreDao() {
        return scoreDao;
    }

    public GroupDao getGroupDao() {
        return groupDao;
    }

}
